CREATE TABLE [ods].[Fanmaker_Social_Interactions_Historical]
(
[User ID] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Username] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[First Name] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Last Name] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Last Seen] [datetime] NULL,
[Member ID] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Current Membership Level] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Student ID] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Ticketmaster ID] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Customer ID] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Outbox ID] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PID] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GPSID] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RFID] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Tags] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Desktop Visits] [bigint] NULL,
[Mobile Web Visits] [bigint] NULL,
[Mobile App Visits] [bigint] NULL,
[Total Visits] [numeric] (18, 0) NULL,
[Type] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Subtype] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Date] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Subject] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Awarded] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Help Text] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Link] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
