CREATE TABLE [ods].[NCR_SalesHeaders]
(
[ETL_ID] [int] NOT NULL IDENTITY(1, 1),
[ETL_CreatedDate] [datetime] NOT NULL CONSTRAINT [DF__NCR_Sales__ETL_C__0572C51D] DEFAULT (getdate()),
[ETL_UpdatedDate] [datetime] NOT NULL CONSTRAINT [DF__NCR_Sales__ETL_U__0666E956] DEFAULT (getdate()),
[ETL_IsDeleted] [bit] NOT NULL CONSTRAINT [DF__NCR_Sales__ETL_I__075B0D8F] DEFAULT ((0)),
[ETL_DeletedDate] [datetime] NULL,
[ETL_DeltaHashKey] [binary] (32) NULL,
[ETL_SourceFileName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BUS_DAT] [date] NULL,
[DOC_ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EVENT_NO] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR_ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STA_ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TKT_NO] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DOC_GUID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TKT_DAT] [date] NULL,
[TKT_TIM] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STK_LOC_ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CUST_NO] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LOY_PGM_COD] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SHIP_VIA_COD] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TAX_COD] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SAL_LINS] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SAL_LIN_TOT] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RET_LINS] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RET_LIN_TOT] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GFC_LINS] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SVC_LINS] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LINS] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SUB_TOT] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TOT_DISC] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TOT_COST] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TOT_WEIGHT] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TOT_CUBE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TOT_MISC] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TAX_AMT] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TOT_TND] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TOT_CHNG] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NET_TND] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TOT] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PAY_AMT] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EC_ORD_NO] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BILL_NAM] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BILL_ADRS_1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BILL_ADRS_2] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BILL_CITY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BILL_STATE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BILL_ZIP_COD] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BILL_CNTRY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BILL_PHONE_1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BILL_PHONE_2] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BILL_EMAIL_ADRS_1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BILL_EMAIL_ADRS_2] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SHIP_NAM] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SHIP_ADRS_1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SHIP_ADRS_2] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SHIP_CITY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SHIP_STATE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SHIP_ZIP_COD] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SHIP_CNTRY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SHIP_PHONE_1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SHIP_PHONE_2] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SHIP_EMAIL_ADRS_1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SHIP_EMAIL_ADRS_2] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ORIG_ORD_STR_ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ORIG_ORD_NO] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LST_MAINT_DT] [date] NULL,
[CARD_NAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CARD_NO] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CARD_TYPE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
