CREATE TABLE [ods].[Bypass_BACKUP_Orders]
(
[ETL__ID] [int] NOT NULL IDENTITY(1, 1),
[ETL__CreatedDate] [datetime] NULL,
[ETL__UpdatedDate] [datetime] NULL,
[id] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[state] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[friendly_id] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[name] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[created_at] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[total] [decimal] (13, 4) NULL,
[tippable] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tip] [decimal] (13, 4) NULL,
[updated_at] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[errors] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[uuid] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[subtotal] [decimal] (13, 4) NULL,
[seat] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[seat_number] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[order_taker_name] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[discounts_total] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[sales_tax_total] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[surcharge] [decimal] (13, 4) NULL,
[balance_due] [decimal] (13, 4) NULL,
[device_serial_number] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[location_id] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[service_location_id] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[loyalty_account] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[number_of_guests] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[vendor_id] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[venodr_name] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[vendor_description] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[concession] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[section] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[row] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[gratuity_configuration_snapshot] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
