CREATE TABLE [segmentation].[SegmentationFlatData59f847b4-ea37-44ca-b41d-16991b2a9126]
(
[id] [uniqueidentifier] NOT NULL,
[DocumentType] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SessionId] [varchar] (36) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Environment] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TenantId] [varchar] (36) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[_rn] [bigint] NULL,
[SSB_CRMSYSTEM_CONTACT_ID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[anniversary] [datetime] NULL,
[annualincome] [money] NULL,
[annualincome_base] [money] NULL,
[birthdate] [datetime] NULL,
[childrensnames] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_201314sohcustomer] [bit] NULL,
[client_201314sohcustomername] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_additionalthoughtsteamandpalyers] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_additionalthoughtswildsatisfaction] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_anythingelsewildexperience] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_attendancecategory] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_averagecost] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_avgsportsevtsperyear] [decimal] (28, 0) NULL,
[client_birthdate] [datetime] NULL,
[client_blockpurchasedprice] [money] NULL,
[client_blockpurchasedprice_base] [money] NULL,
[client_brokerflag] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_businessmaintel] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_cdoflag] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_childrenpresent] [nvarchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_childrenpresentinhh] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_closedgroupoppnotthisseason] [bit] NULL,
[client_closedgroupoppnotthisseasonname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_closedgroupoppthisseason] [bit] NULL,
[client_closedgroupoppthisseasonname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_closedticketoppthisseason] [bit] NULL,
[client_closedticketoppthisseasonname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_compltedtps] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_contactid] [uniqueidentifier] NULL,
[client_currentseasonadditionaltickets] [int] NULL,
[client_cust_name_id] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_dateofform] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_dii] [nvarchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_disttoclientvenue] [nvarchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_emaillastmodifieddate] [datetime] NULL,
[client_estannualhhincome] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_event_name] [nvarchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_eventcode] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_fanrelationsticketgroup] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_fencesitter] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_fse_value] [decimal] (28, 0) NULL,
[client_fsevalue] [decimal] (28, 0) NULL,
[client_fullplanscore] [nvarchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_fullymissedgames] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_game] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_game1date] [datetime] NULL,
[client_game1message] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_game2date] [datetime] NULL,
[client_game2message] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_game3date] [datetime] NULL,
[client_game3message] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_game4message] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_game5message] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_game6message] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_game7message] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_gamedate4] [datetime] NULL,
[client_gamespurchased] [int] NULL,
[client_groupformspecialrequestandcomments] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_groupticketoppforcurrentseason] [bit] NULL,
[client_groupticketoppforcurrentseasonname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_halfplanscore] [nvarchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_hooverscompanyname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_incementalinvestment] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_initialmembershippackagesent] [bit] NULL,
[client_initialmembershippackagesentname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_inputindoccupation] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_kidsclubmembershippaid] [bit] NULL,
[client_kidsclubmembershippaidname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_kidsclubmembertype] [int] NULL,
[client_kidsclubmembertypename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_kidsclubpaymentstatus] [int] NULL,
[client_kidsclubpaymentstatusname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_kidsclubpaymenttype] [int] NULL,
[client_kidsclubpaymenttypename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_lifestyleattribute1] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_likelihoodtorenew] [nvarchar] (26) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_mailorderdonor] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_mergetoeloqua] [bit] NULL,
[client_mergetoeloquaname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_millitaryaffiliation] [bit] NULL,
[client_millitaryaffiliationname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_monthsincelastevent] [nvarchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_monthssincelastpurch] [nvarchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_multipleticketopps] [int] NULL,
[client_nextautofollowupdate] [datetime] NULL,
[client_numberofkids] [int] NULL,
[client_numberofseats] [int] NULL,
[client_numberoftickets] [int] NULL,
[client_numofticketops] [int] NULL,
[client_numoftouchpoints] [int] NULL,
[client_numseats] [nvarchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_ofseats_game1] [int] NULL,
[client_ofseats_game1name] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_oldemail] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_opengroupoppnotthisseason] [bit] NULL,
[client_opengroupoppnotthisseasonname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_opengroupoppthisseason] [bit] NULL,
[client_opengroupoppthisseasonname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_opportunitythisyear] [bit] NULL,
[client_opportunitythisyearname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_paidamount] [money] NULL,
[client_paidamount_base] [money] NULL,
[client_paymentplanoptions] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_personicxcluster] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_personicxgroup] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pin] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_plangrade] [nvarchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_planscore] [nvarchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_plantypeforrenewal] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_planvalue] [money] NULL,
[client_planvalue_base] [money] NULL,
[client_postaltrackingnumber] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_premiumseatingemailquestion] [int] NULL,
[client_premiumseatingemailquestionname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_primary_age] [int] NULL,
[client_product] [int] NULL,
[client_productname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_promocode] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_repinterenallimitemail] [bit] NULL,
[client_repinterenallimitemailname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_satisfactionbuildingacompetitiveteam] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_satisfactionfanrelationsrep] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_scheduledtime] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_signupdate] [datetime] NULL,
[client_singleplanscore] [nvarchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_sm_abilitytoreselltickets] [int] NULL,
[client_sm_overallgamedayexperience] [int] NULL,
[client_sm_playoffpriority] [int] NULL,
[client_sm_teamperformance] [int] NULL,
[client_sm_ticketprices] [int] NULL,
[client_sm_timeconstraints] [int] NULL,
[client_smstexttrigger] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_sthprofilecompleteness] [float] NULL,
[client_suggestedpackage] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_tenurecategory] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_tixpricegrade] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_tixpricescore] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_tkteventprice101201] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_totalkidclubmemberships] [int] NULL,
[client_totalspent] [int] NULL,
[client_totalspentdollars] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_totseasspndgrade] [nvarchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_totseasspndscore] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_totsportsevents] [nvarchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_totsportsspend] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_touchpointid] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_touchpointlookup] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_unidentifiedpartner] [int] NULL,
[client_unidentifiedpartnername] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_upgradefrom] [int] NULL,
[client_upgradefromname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_wildenews] [bit] NULL,
[client_wildenewsname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_wildfanrelationsrep] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_wildticketgroup] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_wrhasloggedin] [bit] NULL,
[client_wrhasloggedinname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_wrnooflogins] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_wrpromopoints] [int] NULL,
[client_wrroadgamepoints] [int] NULL,
[client_wrsocialmediapoints] [int] NULL,
[client_wrspecialeventspoints] [int] NULL,
[cm_donotsms] [bit] NULL,
[cm_donotsmsname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cm_isanonymous] [bit] NULL,
[cm_isanonymousname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cm_leadscore] [int] NULL,
[contactid] [uniqueidentifier] NOT NULL,
[createdby] [uniqueidentifier] NULL,
[createdbyname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[createdbyyominame] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[createdon] [datetime] NULL,
[createdonbehalfby] [uniqueidentifier] NULL,
[createdonbehalfbyname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[createdonbehalfbyyominame] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[creditonhold] [bit] NULL,
[creditonholdname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[customersizecode] [int] NULL,
[customersizecodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[customertypecode] [int] NULL,
[customertypecodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[donotbulkemail] [bit] NULL,
[donotbulkemailname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[donotbulkpostalmail] [bit] NULL,
[donotbulkpostalmailname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[donotemail] [bit] NULL,
[donotemailname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[donotfax] [bit] NULL,
[donotfaxname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[donotphone] [bit] NULL,
[donotphonename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[donotpostalmail] [bit] NULL,
[donotpostalmailname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[donotsendmarketingmaterialname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[donotsendmm] [bit] NULL,
[kore_checkedoutby] [uniqueidentifier] NULL,
[kore_checkedoutbyname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_checkedoutbyyominame] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_checkedoutuntil] [datetime] NULL,
[kore_groupbuyername] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_groupcategory] [int] NULL,
[kore_groupcategoryname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_groupsalesrep] [uniqueidentifier] NULL,
[kore_groupsalesrepname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_groupsalesrepyominame] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_heritagenationality] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_importid] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_invoicebalance] [money] NULL,
[kore_invoicebalance_base] [money] NULL,
[kore_lastcontacted] [datetime] NULL,
[kore_lastcontactedbyid] [uniqueidentifier] NULL,
[kore_lastcontactedbyidname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_lastcontactedbyidyominame] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_lastsync] [datetime] NULL,
[kore_listattributename] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_listattributevalue] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_managerphonedncstatus] [bit] NULL,
[kore_managerphonedncstatusname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_milesfromfacility] [decimal] (28, 0) NULL,
[kore_miniplanholder] [bit] NULL,
[kore_miniplanholdername] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_mobilephonedncstatus] [bit] NULL,
[kore_mobilephonedncstatusname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_optoutofduplicatedetection] [bit] NULL,
[kore_optoutofduplicatedetectionname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_overridecheckoutexpiration] [bit] NULL,
[kore_overridecheckoutexpirationname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_parentcustomeridstrippedname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_primaryaccountnumber] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_primaryarchticsid] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_seasonticketholder] [bit] NULL,
[kore_seasonticketholdername] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_secondaryarchticsname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_secondaryemail] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_senioritydate] [datetime] NULL,
[kore_sincedate] [datetime] NULL,
[kore_sourcemarketinglistid] [uniqueidentifier] NULL,
[kore_sourcemarketinglistidname] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_stateorprovinceid] [uniqueidentifier] NULL,
[kore_stateorprovinceidname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_suitebuyer] [bit] NULL,
[kore_suitebuyername] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_suitesalesrep] [uniqueidentifier] NULL,
[kore_suitesalesrepname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_suitesalesrepyominame] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_ticketingcontacttype] [int] NULL,
[kore_ticketingcontacttypename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_ticketingsalesrep] [uniqueidentifier] NULL,
[kore_ticketingsalesrepname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_ticketingsalesrepyominame] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_ticketingservicerep] [uniqueidentifier] NULL,
[kore_ticketingservicerepname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_ticketingservicerepyominame] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_ticketingtype] [int] NULL,
[kore_ticketingtypename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_type] [int] NULL,
[kore_typename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps_accountstrippedname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps_appointmentsin90days] [int] NULL,
[koreps_callsin90days] [int] NULL,
[koreps_companyid] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps_consecutivemissedgames] [int] NULL,
[koreps_consecutiveseasons] [int] NULL,
[koreps_contacttype] [int] NULL,
[koreps_contacttypename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps_disablecontactsync] [bit] NULL,
[koreps_disablecontactsyncname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps_donotstream] [bit] NULL,
[koreps_donotstreamname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps_emailsin90days] [int] NULL,
[koreps_ficoscore] [int] NULL,
[koreps_invalidemail] [bit] NULL,
[koreps_invalidemailname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps_lastcontacted] [datetime] NULL,
[koreps_nextbirthday] [datetime] NULL,
[koreps_purchasedseasons] [int] NULL,
[koreps_seasonattendancebygames] [float] NULL,
[koreps_seasonattendancebyseats] [float] NULL,
[koreps_syncpriority] [int] NULL,
[koreps_tenure] [int] NULL,
[koreps_ticketingaccounttype] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps_ticketingcontacttype] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lastusedincampaign] [datetime] NULL,
[leadsourcecode] [int] NULL,
[leadsourcecodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[managername] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[managerphone] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[mastercontactidname] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[mastercontactidyominame] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[masterid] [uniqueidentifier] NULL,
[modifiedby] [uniqueidentifier] NULL,
[modifiedbyname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[modifiedon] [datetime] NULL,
[modifiedonbehalfby] [uniqueidentifier] NULL,
[modifiedonbehalfbyname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[modifiedonbehalfbyyominame] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ownerid] [uniqueidentifier] NULL,
[owneridname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[owneridtype] [nvarchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[parentcontactidname] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[parentcustomerid] [uniqueidentifier] NULL,
[parentcustomeridname] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[parentcustomeridtype] [nvarchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[parentcustomeridyominame] [nvarchar] (450) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[participatesinworkflow] [bit] NULL,
[participatesinworkflowname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[paymenttermscode] [int] NULL,
[paymenttermscodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[preferredappointmentdaycode] [int] NULL,
[preferredappointmentdaycodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[preferredappointmenttimecode] [int] NULL,
[preferredappointmenttimecodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[preferredcontactmethodcode] [int] NULL,
[preferredcontactmethodcodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[preferredequipmentid] [uniqueidentifier] NULL,
[preferredequipmentidname] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[preferredserviceid] [uniqueidentifier] NULL,
[preferredserviceidname] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[preferredsystemuseridname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[processid] [uniqueidentifier] NULL,
[stageid] [uniqueidentifier] NULL,
[statecode] [int] NULL,
[statecodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[statuscode] [int] NULL,
[statuscodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
ALTER TABLE [segmentation].[SegmentationFlatData59f847b4-ea37-44ca-b41d-16991b2a9126] ADD CONSTRAINT [pk_SegmentationFlatData59f847b4-ea37-44ca-b41d-16991b2a9126] PRIMARY KEY NONCLUSTERED  ([id])
GO
