CREATE TABLE [segmentation].[SegmentationFlatDatafe79e479-6f60-46bd-8655-5ff5ade9d057]
(
[id] [uniqueidentifier] NOT NULL,
[DocumentType] [varchar] (17) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SessionId] [varchar] (36) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Environment] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TenantId] [varchar] (36) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[_rn] [bigint] NULL,
[SSB_CRMSYSTEM_CONTACT_ID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_attendance] [float] NULL,
[client_delivery] [int] NULL,
[client_directornote] [int] NULL,
[client_directorphonecall] [int] NULL,
[client_fanrelationssatisfaction] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_handnote] [int] NULL,
[client_inseatvisitinarena] [int] NULL,
[client_lastgroupdeclinereason] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_lastseasongrouprevenue] [int] NULL,
[client_lastseasongroupseats] [int] NULL,
[client_lasttouchpointcompleted] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_lasttouchpointdate] [datetime] NULL,
[client_likelihoodtorenew] [nvarchar] (26) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_outofofficevisit] [int] NULL,
[client_overallsatisfaction] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_phonecall] [int] NULL,
[client_plantype] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_specialevent] [int] NULL,
[client_stadiumseries] [bit] NULL,
[client_stadiumseriesname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_teamperfomancesatisfaction] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_tenure] [int] NULL,
[client_wrlogins] [int] NULL,
[createdbyname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[createdon] [datetime] NULL,
[createdonbehalfbyname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps_currentcost] [money] NULL,
[koreps_currentcost_base] [money] NULL,
[koreps_currentperceivedvalue] [money] NULL,
[koreps_currentperceivedvalue_base] [money] NULL,
[koreps_currentpoints] [int] NULL,
[koreps_enddate] [datetime] NULL,
[koreps_name] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps_pointsremaining] [int] NULL,
[koreps_seasonidname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps_startdate] [datetime] NULL,
[koreps_targetvalue] [int] NULL,
[modifiedbyname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[modifiedon] [datetime] NULL,
[modifiedonbehalfbyname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[owneridname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[statecode] [int] NULL,
[statecodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[statuscode] [int] NULL,
[statuscodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
ALTER TABLE [segmentation].[SegmentationFlatDatafe79e479-6f60-46bd-8655-5ff5ade9d057] ADD CONSTRAINT [pk_SegmentationFlatDatafe79e479-6f60-46bd-8655-5ff5ade9d057] PRIMARY KEY NONCLUSTERED  ([id])
GO
CREATE CLUSTERED INDEX [cix_SegmentationFlatDatafe79e479-6f60-46bd-8655-5ff5ade9d057] ON [segmentation].[SegmentationFlatDatafe79e479-6f60-46bd-8655-5ff5ade9d057] ([_rn])
GO
