CREATE TABLE [segmentation].[SegmentationFlatData8ada55c4-aac4-41dd-8bea-5ec8a1b58a74]
(
[id] [uniqueidentifier] NOT NULL,
[DocumentType] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SessionId] [varchar] (36) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Environment] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TenantId] [varchar] (36) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[_rn] [bigint] NULL,
[SSB_CRMSYSTEM_CONTACT_ID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_contestteamname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_currentpaymentplan] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_fencesittertype] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_fse] [float] NULL,
[client_originalplanvalue] [float] NULL,
[client_plantypes] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_renewalstatus] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_rrpointshavebeendeposited] [bit] NULL,
[client_rrpointshavebeendepositedname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_wildrewardsrenewalincentive] [bit] NULL,
[client_wildrewardsrenewalincentivename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[createdbyname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[createdon] [datetime] NULL,
[createdonbehalfbyname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_account] [uniqueidentifier] NULL,
[kore_accountname] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_boxofficeusername] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_campaign] [uniqueidentifier] NULL,
[kore_campaignname] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_completedtasks] [int] NULL,
[kore_datewon] [datetime] NULL,
[kore_declineorderreason] [int] NULL,
[kore_declineorderreasonname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_declineorderreasonother] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_estimatedclosedate] [datetime] NULL,
[kore_name] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_nextscheduledactivity] [datetime] NULL,
[kore_numberoftickets] [int] NULL,
[kore_opportunitysize] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_paymentdetails] [int] NULL,
[kore_paymentdetailsname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_paymentplan] [int] NULL,
[kore_paymentplanname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_primaryobjection] [int] NULL,
[kore_primaryobjectionname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_product] [int] NULL,
[kore_productname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_rating] [int] NULL,
[kore_ratingname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_reasonforbuying] [int] NULL,
[kore_reasonforbuyingname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_salesstep] [int] NULL,
[kore_salesstepname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_salestype] [int] NULL,
[kore_salestypename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_season] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_submitforanotherrep] [bit] NULL,
[kore_submitforanotherrepname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_submittousername] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_ticketorderdate] [datetime] NULL,
[kore_ticketorderprocessedon] [datetime] NULL,
[kore_ticketordertype] [int] NULL,
[kore_ticketordertypename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps_addons] [nvarchar] (900) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps_addonsother] [nvarchar] (600) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps_conversation] [bit] NULL,
[koreps_conversationname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps_leadsource] [int] NULL,
[koreps_leadsourcename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps_numberoftickets2] [int] NULL,
[koreps_oppsize] [money] NULL,
[koreps_oppsize_base] [money] NULL,
[koreps_oppsize2] [money] NULL,
[koreps_oppsize2_base] [money] NULL,
[modifiedbyname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[modifiedon] [datetime] NULL,
[modifiedonbehalfby] [uniqueidentifier] NULL,
[modifiedonbehalfbyname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[overriddencreatedon] [datetime] NULL,
[owneridname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[owneridtype] [nvarchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[statecode] [int] NULL,
[statecodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[statuscode] [int] NULL,
[statuscodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
ALTER TABLE [segmentation].[SegmentationFlatData8ada55c4-aac4-41dd-8bea-5ec8a1b58a74] ADD CONSTRAINT [pk_SegmentationFlatData8ada55c4-aac4-41dd-8bea-5ec8a1b58a74] PRIMARY KEY NONCLUSTERED  ([id])
GO
CREATE CLUSTERED INDEX [cix_SegmentationFlatData8ada55c4-aac4-41dd-8bea-5ec8a1b58a74] ON [segmentation].[SegmentationFlatData8ada55c4-aac4-41dd-8bea-5ec8a1b58a74] ([_rn])
GO
