CREATE TABLE [src].[Eloqua_Custom_WildPreferenceCenter]
(
[ETL_ID] [int] NOT NULL IDENTITY(1, 1),
[ETL_CreatedDate] [datetime] NOT NULL CONSTRAINT [DF__Eloqua_Cu__ETL_C__364019AA] DEFAULT (getdate()),
[ID] [int] NOT NULL,
[Birthdate11] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Birthdate_Fix1] [date] NULL,
[Email_Address1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[First_Name1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Last_Name1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MS_CRM_Account_ID1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MS_CRM_Contact_ID1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Account_ID1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FanRelationsContactByEmail1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FanRelationsContactByText1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FanRelationsContactByPhone1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FanRelationsContactByMail1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FanRelationsContactByFacetoFace1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Military_Affiliation1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TeamCommByEmail1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TeamCommByText1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TeamCommByFacebook1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TeamCommByTwitter1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CommPreferencesGameDayInfo1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CommPreferencesTicketInfoAlerts1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CommPreferencesWildEnews1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[New_Email_Address1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Mobile_Phone1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Business_Phone1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Home_Phone1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gender1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Title1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Favorite_Player1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FavoritePlayer21] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FavoritePlayer31] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Favorite_Opponent__11] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Favorite_Opponent__21] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[College_Name1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[What_is_your_favorite_Wild_memory_21] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Spouse_First_Name1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Spouse_Birthdate1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Spouse_Birthday_11] [date] NULL,
[Do_you_have_children_1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NumberOfChildren1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Child__1_Name1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Child__1_Birthdate1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Child_1_Birthdate_11] [date] NULL,
[Child__1_Favorite_Player1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Child_1_Relationship1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Child__2_Name1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Child__2_Birthdate1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Child__2_Birthdate_11] [date] NULL,
[Child_2_Relationship1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Child__2_Favorite_Player1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Child__3_Name1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Child_3_Relationship1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Child__3_Favorite_Player1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Child__3_Birthdate1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Child__3_Birthdate_11] [date] NULL,
[Child__4_Name1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Child__4_Birthdate1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Child__4_Birthdate_11] [date] NULL,
[Child_4_Relationship1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Child__4_Favorite_Player1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Child__5_Name1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Child__5_Birthdate1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Child__5_Birthdate_11] [date] NULL,
[Child_5_Relationship1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Child__5_Favorite_Player1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Youth_Hockey_Association1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Dogs1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Dog1Name1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Dog1BIrthdate1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Dog_Birthday1] [date] NULL,
[Dog1Gender1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cats1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cat1Name1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cat1Birthdate1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cat_Birthday1] [date] NULL,
[Cat1Gender1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Other1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OtherPet1Name1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OtherPet1Birthdate1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Other_Pet_Birthday1] [date] NULL,
[OtherPet1Gender1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OtherPet1Type1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Do_you_use_a_smartphone_1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gifts1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Donation_to_Charity1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[What_nonprofit_organizations_are_you_affiliat1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RestaurantsFirstChoice1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OtherRestaurant11] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RestaurantsSecondChoice1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OtherRestaurantsSecondChoice1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ParkingRamp1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OtherParkingRamp1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Alternative1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Jazz1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Hard_Rock1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Hip_Hop1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Antiques1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Baseball1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Camping1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cooking1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Craft_Beer1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fishing1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Golf1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Hunting1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Movies1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Outdoor_Activities1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reading1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Snowboarding1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Video_Games1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Wine_Tasting1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OtherHobbies1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OtherHobbiesText1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Vikings1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Timberwolves1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gophers1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Lynx1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Twins1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[United_FC1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[What_is_your_favorite_restaurant_in_the_Twin_1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[What_is_your_favorite_travel_destination_1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Travel1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Skiing1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Pets1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Music1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Martial_Arts1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Hockey1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Football1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Family_Fun1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Crafts1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Collectibles1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Basketball1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Art1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Top_401] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Classical1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Country1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[What_is_the_primary_direction_you_arrive_from1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Personal_Use1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Friends_Family1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Business1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Spouse_Favorite_Player1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Spouse_Last_Name1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Spouse_Email_Address1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Are_you_married_1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Wedding_Anniversary1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Wedding_Anniversary_11] [date] NULL,
[Company1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
ALTER TABLE [src].[Eloqua_Custom_WildPreferenceCenter] ADD CONSTRAINT [PK__Eloqua_C__3214EC27B671350E] PRIMARY KEY CLUSTERED  ([ID])
GO
