CREATE TABLE [stg].[NCR_SalesLineItems]
(
[ETL_ID] [int] NOT NULL IDENTITY(1, 1),
[ETL_CreatedDate] [datetime] NOT NULL CONSTRAINT [DF__NCR_Sales__ETL_C__0B2B9E73] DEFAULT (getdate()),
[ETL_SourceFileName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BUS_DAT] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DOC_ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LIN_SEQ_NO] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EVENT_NO] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR_ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STA_ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TKT_NO] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LIN_GUID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LIN_TYP] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PAR_ITEM_NO] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KIT_COMP_QTY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STK_LOC_ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BARCOD] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ITEM_NO] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DESCR] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CATEG_COD] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SUBCAT_COD] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CATEG_SUBCAT] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ITEM_VEND_NO] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ITEM_TYP] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TRK_METH] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IS_TXBL] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[QTY_SOLD] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SELL_UNIT] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[QTY_SOLD_STK_UNIT] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PRC_1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PRC] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COST] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EXT_COST] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EXT_PRC] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DIM_1_UPR] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DIM_2_UPR] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DIM_3_UPR] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LST_MAINT_DT] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
