IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'SSBINFO\kwyss')
CREATE LOGIN [SSBINFO\kwyss] FROM WINDOWS
GO
CREATE USER [SSBINFO\kwyss] FOR LOGIN [SSBINFO\kwyss] WITH DEFAULT_SCHEMA=[SSBINFO\kwyss]
GO
REVOKE CONNECT TO [SSBINFO\kwyss]
