CREATE SCHEMA [api]
AUTHORIZATION [dbo]
GO
GRANT EXECUTE ON SCHEMA:: [api] TO [db_svcLogi]
GO
GRANT DELETE ON SCHEMA:: [api] TO [svcssbrp]
GO
GRANT EXECUTE ON SCHEMA:: [api] TO [svcssbrp]
GO
GRANT INSERT ON SCHEMA:: [api] TO [svcssbrp]
GO
GRANT SELECT ON SCHEMA:: [api] TO [svcssbrp]
GO
GRANT UPDATE ON SCHEMA:: [api] TO [svcssbrp]
GO
