CREATE SCHEMA [mdm]
AUTHORIZATION [dbo]
GO
GRANT DELETE ON SCHEMA:: [mdm] TO [svcssbrp]
GO
GRANT EXECUTE ON SCHEMA:: [mdm] TO [svcssbrp]
GO
GRANT INSERT ON SCHEMA:: [mdm] TO [svcssbrp]
GO
GRANT SELECT ON SCHEMA:: [mdm] TO [svcssbrp]
GO
GRANT UPDATE ON SCHEMA:: [mdm] TO [svcssbrp]
GO
