CREATE SCHEMA [stg]
AUTHORIZATION [SSBCLOUD\shegde]
GO
GRANT DELETE ON SCHEMA:: [stg] TO [svcssbrp]
GO
GRANT EXECUTE ON SCHEMA:: [stg] TO [svcssbrp]
GO
GRANT INSERT ON SCHEMA:: [stg] TO [svcssbrp]
GO
GRANT SELECT ON SCHEMA:: [stg] TO [svcssbrp]
GO
GRANT UPDATE ON SCHEMA:: [stg] TO [svcssbrp]
GO
